# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
url:                 http://www.seth-dehaan.com

# Setup
title:               seth.blog
tagline:             rambling and rambling
paginate:            5
baseurl:             ""
gems:                [jekyll-paginate, kramdown]
markdown:            kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Prose.io configuration
prose:
  media: "assets"
  siteurl: "http://www.seth-dehaan.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "insert title here"
      - name: "desc"
        field:
          label: "meta-description"
          element: "text"
          value: "meta-description"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          value: "tags"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "insert title here"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Seth DeHaan
  url:               https://twitter.com/sethdehaan
  email:             seth.dehaan@gmail.com

# sitemap configuration
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sethxd/sethxd.github.io

# Dictionary of pages
pages_list:
  About: '/about'
  Archive: '/archive'
  Projects: '/projects'
  Feed: '/atom.xml'
