# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               seth.blog
tagline:             rambling and rambling
paginate:            5
baseurl:             ""
gems:                [jekyll-paginate]
markdown:            kramdown
highlighter:         pygments

# Prose.io configuration
prose:
  media: "assets"
  siteurl: "http://www.seth-dehaan.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "description"
        field:
          label: "meta-description"
          element: "text"
          value: "meta-description"
      - name: "tags"
        field:
          label: "tags"
          element: "text"
          value: "tags"
      - name: "title"
      	field:
          label: "title"
          element: "text"
          value: "insert title here"
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Seth DeHaan
  url:               https://twitter.com/sethdehaan
  email:             seth.dehaan@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sethxd/sethxd.github.io

# Dictionary of pages
pages_list:
  About: '/about'
  Archive: '/archive'
  Projects: '/projects'
  Feed: '/atom.xml'
